Backend/LawyersFirm/Controllers/AboutController.cs
using LawyersFirm.Data;
using LawyersFirm.Models;
using Microsoft.AspNetCore.Mvc;

namespace LawyersFirm.Controllers
{
    public class AboutController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AboutController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var newContact = new Contact();
            return View(newContact);
        }

        //POST: Contact Form
        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Contact.Add(contact);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contact);
        }
    }
}

Backend/LawyersFirm/Controllers/AdminController.cs
using LawyersFirm.Data;
using Microsoft.AspNetCore.Mvc;

namespace LawyersFirm.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var adminSession = HttpContext.Session.GetString("Username");
            if (adminSession == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }
    }
}

Backend/LawyersFirm/Controllers/CareerController.cs
using LawyersFirm.Data;
using Microsoft.AspNetCore.Mvc;

namespace LawyersFirm.Controllers
{
    public class CareerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CareerController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var jobList = _context.Job.ToList();
            return View(jobList);
        }
    }
}

Backend/LawyersFirm/Controllers/ContactController.cs
using LawyersFirm.Data;
using LawyersFirm.Models;
using Microsoft.AspNetCore.Mvc;

namespace LawyersFirm.Controllers
{
    public class ContactController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var newContact = new Contact();
            return View(newContact);
        }
      
        //POST: Contact Form
        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Contact.Add(contact);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contact);
        }
    }
}

Backend/LawyersFirm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nomaan & Associates</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gwendolyn:wght@400;700&family=Lobster&family=Playwrite+DK+Loopet:wght@100..400&family=Quicksand:wght@300..700&family=Varela+Round&display=swap" rel="stylesheet">
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <!-- Bootstrap 4 cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/Style.css" />
    @* <link rel="stylesheet" href="~/LawyersFirm.styles.css" asp-append-version="true" /> *@
    <!-- fonawesome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <!-- aso library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">

    <link rel="icon" href="~/img/logo.png">

</head>
<body style="background-color: #FFF2E1; color: #800000;">
    <header>
        <!-- nav-bar starts -->
        <div class="navbar-container">
            <img src="~/img/logo.png" alt="Logo" class="logo" width="100" height="auto">
            <div class="hamburger" onclick="toggleMenu()">
                <div></div>
                <div></div>
                <div></div>
            </div>
            <div class="navbar">
                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" asp-controller="About" asp-action="Index">About</a>
                <a asp-area="" asp-controller="Service" asp-action="Index">Services</a>
                <a asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                <a asp-area="" asp-controller="Career" asp-action="Index">Career</a>
                <a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
            </div>
        </div>
        <!-- nav-bar ends -->
    </header>
    <div class="">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <section class="footer">

            <div class="foot-box-main">
                <div class="foot-content">
                    <div class="foot-pages">
                        <h3>Pages</h3>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a asp-controller="About" asp-action="Index">About</a>
                        <a asp-controller="Service" asp-action="Index">Services</a>
                        <a asp-controller="Contact" asp-action="Index">Contact</a>
                        <a asp-controller="Career" asp-action="Index">Career</a>
                        <a asp-controller="Admin" asp-action="Index">Admin</a>
                    </div>
                    <div class="foot-contact-me">
                        <h3>Contact Me</h3>
                        <div class="foot-contact-me-row">

                            <img src="~/img/Phone-light.png"><p>+91 790 561 4885</p>
                        </div>
                        <div class="foot-contact-me-row">
                            <img src="~/img/Email-light.png"><p>contact@nomaanadmadsiddiqui.com</p>
                        </div>
                        <div class="foot-contact-me-row">
                            <img src="~/img/Website-light.png"><p>www.nomaanahmadsiddiqui.com</p>
                        </div>
                        <div class="foot-contact-me-row">
                            <img src="~/img/Address-light.png"><p>Aqsa Manzil, near Islamia College,<br />Lalbagh, Lucknow, <br />Uttar Pradesh, <br />Pin: 226001</p>
                        </div>
                    </div>
                    <div class="foot-social">
                        <h3>Social Connect</h3>
                        <div class="foot-social-icons">
                            <a href="https://www.linkedin.com/in/nomaan-ahmad-siddiqui-9b995a177/?originalSubdomain=in" target="_blank"><img src="~/img/linkedin-light.png"></a>
                            <a href="https://www.instagram.com/adv.nomaanahmadsiddiqui/?igsh=amVjYTZsOW5xZ2R4" target="_blank"><img src="~/img/instagram-light.png"></a>
                            <a href="https://wa.me/917905614885" target="_blank"><img src="~/img/whatsapp-light.png"></a>
                            <a href="#"><img src="~/img/facebook-light.png"></a>
                        </div>
                    </div>
                    <div class="foot-login">
                        <h3>Account Login</h3>
                        <div class="foot-login-area">
                            <a asp-controller="Login" asp-action="Index"><img src="~/img/Login-light.png" onclick="window.location.href='Login.html'" class="mr-2">LOGIN</a>
                        </div>
                    </div>
                </div>
                <div class="foot-developer">
                    <a asp-controller="Home" asp-action="SayedAsadJamal" style="text-decoration: none; color:#fff">Developed by Sayed Asad Jamal | 2024</a>
                </div>
            </div>
        </section>
    </footer>
    @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@
    <script src="~/js/JavaScript.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>