Backend/LawyersFirm/Controllers/EmailsController.cs
using LawyersFirm.Data;
using Microsoft.AspNetCore.Mvc;

namespace LawyersFirm.Controllers
{
    public class EmailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmailsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string searchQuery = "", int page = 1, int pageSize = 5)
        {
            //Check if user logged in
            var adminSession = HttpContext.Session.GetString("Username");
            if (adminSession == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var contactsQuery = _context.Contact.AsQueryable();

            if (!string.IsNullOrEmpty(searchQuery))
            {
                contactsQuery = contactsQuery.Where(c => c.Name.Contains(searchQuery)
                                                       || c.Email.Contains(searchQuery)
                                                       || c.Phone.Contains(searchQuery));
            }

            var totalCount = contactsQuery.Count();
            var emailList = contactsQuery
                            .OrderByDescending(c => c.CreatedOn)
                            .Skip((page - 1) * pageSize)
                            .Take(pageSize)
                            .ToList();

            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalCount = totalCount;
            ViewBag.SearchQuery = searchQuery;

            return View(emailList);
        }

    }
}

Backend/LawyersFirm/Controllers/JobController.cs
using LawyersFirm.Data;
using LawyersFirm.Models;
using Microsoft.AspNetCore.Mvc;

namespace LawyersFirm.Controllers
{
    public class JobController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JobController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //Check if user logged in
            var adminSession = HttpContext.Session.GetString("Username");
            if (adminSession == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var jobList = _context.Job.ToList();
            return View(jobList);
        }

        //CREATE: JOBS
        [HttpGet]
        public IActionResult Create()
        {
            //Check if user logged in
            var adminSession = HttpContext.Session.GetString("Username");
            if (adminSession == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var newJob = new Job();
            return View(newJob);
        }

        [HttpPost]
        public IActionResult Create(Job job)
        {
            if (ModelState.IsValid)
            {
                var existPosition = _context.Job.FirstOrDefault(j => j.Position == job.Position && j.Category == job.Category);
                if (existPosition != null)
                {
                    ModelState.AddModelError("Position", "Job for the same position already posted");
                    return View(existPosition);
                }

                _context.Job.Add(job);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(job);
        }

        //UPDATE: JOBs
        [HttpGet]
        public IActionResult Edit(int id)
        {
            //Check if user logged in
            var adminSession = HttpContext.Session.GetString("Username");
            if (adminSession == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var job = _context.Job.Find(id);

            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        [HttpPost]
        public IActionResult Edit(int id, Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Update(job);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(job);
        }

        //Delete
        [HttpGet]
        public IActionResult Delete(int id)
        {
            //Check if user logged in
            var adminSession = HttpContext.Session.GetString("Username");
            if (adminSession == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var existJob = _context.Job.Find(id);

            if (existJob == null)
            {
                return NotFound();
            }

            return View(existJob);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var existJob = _context.Job.Find(id);

            if (existJob != null)
            {
                _context.Job.Remove(existJob);
                _context.SaveChanges();
            }
            return RedirectToAction(("Index"));
        }
    }
}

Backend/LawyersFirm/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Panel";
}

<button id="scrollToTopBtn" title="Go to top">
    <i class="fa-solid fa-up-long"></i>
</button>

<!-- admin-section 1 starts -->
<div class="container pt-lg-5 pb-lg-5 pattern-cls">
    <div class="dot-pattern"></div>
    <div class="text-right">
        <form asp-controller="Login" asp-action="Logout" method="post">
                <button type="submit" class="button shadow">Logout <i class="fa-solid fa-right-from-bracket" style="color: #800000;"></i></button>
        </form>
    </div>

    <h3 class="text-center pb-3 pt-5 gradient-text mb-5">ADMIN PANEL</h3>
    

    <div class="row d-flex align-items-center pb-3">

        <div class="col text-center mb-3 d-flex justify-content-center">
            <div class="admin-card">
                <div class="admin-card-content">
                    <p class="admin-card-title"><a asp-controller="Emails" asp-action="Index" style="text-decoration: none; color: #fff">Emails</a></p>
                    <a asp-controller="Emails" asp-action="Index" style="text-decoration: none; color: #fff"><i class="fa-solid fa-envelope fa-2xl" style="color: #ffffff;"></i></a>
                </div>
            </div>
        </div>

        <div class="col text-center d-flex justify-content-center">
            <div class="admin-card">
                <div class="admin-card-content">
                    <p class="admin-card-title"><a asp-controller="Job" asp-action="Index" style="text-decoration: none; color: #fff">JOBS</a></p>
                    <a asp-controller="Job" asp-action="Index" style="text-decoration: none; color: #fff"><i class="fa-solid fa-users fa-2xl" style="color: #ffffff;"></i></a>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- admin-section 1 ends -->

           